export const defaultScales = [
  [
    [
      { id: 1 },
      { name: 'José Maria' },
      { turn: 'Matutino' },
      { status: true },
      {
        options: [
          { id: 0, type: 'T' },
          { id: 1, type: 'T' },
          { id: 2, type: 'T' },
          { id: 3, type: 'T' },
          { id: 4, type: 'T' },
          { id: 5, type: 'T' },
          { id: 6, type: 'T' },
          { id: 7, type: 'T' },
          { id: 8, type: 'T' },
          { id: 9, type: 'R' },
          { id: 10, type: 'T' },
          { id: 11, type: 'T' },
          { id: 12, type: 'T' },
          { id: 13, type: 'T' },
          { id: 14, type: 'T' },
          { id: 15, type: 'T' },
          { id: 16, type: 'T' },
          { id: 17, type: 'T' },
          { id: 18, type: 'T' },
          { id: 19, type: 'T' },
          { id: 20, type: 'T' },
          { id: 21, type: 'T' },
          { id: 22, type: 'T' },
          { id: 23, type: 'T' },
          { id: 24, type: 'T' },
          { id: 25, type: 'T' },
          { id: 26, type: 'T' },
          { id: 27, type: 'T' },
          { id: 28, type: 'T' },
          { id: 29, type: 'T' },
        ],
      },
    ],
    [
      { id: 2 },
      { name: 'José Maria' },
      { turn: 'Matutino' },
      { status: true },
      {
        options: [
          { id: 0, type: 'R' },
          { id: 1, type: 'T' },
          { id: 2, type: 'T' },
          { id: 3, type: 'T' },
          { id: 4, type: 'T' },
          { id: 5, type: 'T' },
          { id: 6, type: 'T' },
          { id: 7, type: 'T' },
          { id: 8, type: 'T' },
          { id: 9, type: 'T' },
          { id: 10, type: 'T' },
          { id: 11, type: 'T' },
          { id: 12, type: 'T' },
          { id: 13, type: 'T' },
          { id: 14, type: 'T' },
          { id: 15, type: 'T' },
          { id: 16, type: 'T' },
          { id: 17, type: 'T' },
          { id: 18, type: 'T' },
          { id: 19, type: 'T' },
          { id: 20, type: 'T' },
          { id: 21, type: 'T' },
          { id: 22, type: 'T' },
          { id: 23, type: 'T' },
          { id: 24, type: 'T' },
          { id: 25, type: 'T' },
          { id: 26, type: 'T' },
          { id: 27, type: 'T' },
          { id: 28, type: 'T' },
          { id: 29, type: 'T' },
        ],
      },
    ],
  ],
  [
    [
      { type: 'Qnt colab. ativos' },
      {
        values: [
          0, 1, 2, 2, 2, 2, 2, 2, 4, 3, 4, 4, 3, 2, 3, 3, 3, 3, 3, 2, 2, 2, 4,
          3, 3, 2, 2, 3, 4, 2,
        ],
      },
    ],
    [
      { type: 'Atendimento médio' },
      {
        values: [
          0, 1, 1, 1, 1, 1, 2, 2, 4, 3, 4, 9, 10, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2,
          3, 3, 2, 2, 3, 1, 2,
        ],
      },
    ],
    [
      { type: '% Cons. Ativos' },
      {
        values: [
          '0%',
          '98%',
          '98%',
          '98%',
          '98%',
          '98%',
          '98%',
          '98%',
          '98%',
          '98%',
          '100%',
          '100%',
          '100%',
          '100%',
          '133%',
          '100%',
          '133%',
          '100%',
          '100%',
          '100%',
          '100%',
          '100%',
          '100%',
          '100%',
          '98%',
          '100%',
          '100%',
          '133%',
          '100%',
          '100%',
        ],
      },
    ],
  ],
]
