export const dataScales = {
  turns: [
    {
      id: 1,
      name: 'José Maria',
      turn: 'T1',
      options: [
        { id: 0, type: 'T' },
        { id: 1, type: 'T' },
        { id: 2, type: 'T' },
        { id: 3, type: 'T' },
        { id: 4, type: 'T' },
        { id: 5, type: 'T' },
        { id: 6, type: 'T' },
        { id: 7, type: 'T' },
        { id: 8, type: 'T' },
        { id: 9, type: 'T' },
        { id: 10, type: 'T' },
        { id: 11, type: 'T' },
        { id: 12, type: 'T' },
        { id: 13, type: 'T' },
        { id: 14, type: 'T' },
        { id: 15, type: '' },
        { id: 16, type: '' },
        { id: 17, type: '' },
        { id: 18, type: '' },
        { id: 19, type: '' },
        { id: 20, type: '' },
        { id: 21, type: '' },
        { id: 22, type: '' },
        { id: 23, type: '' },
        { id: 24, type: '' },
        { id: 25, type: '' },
        { id: 26, type: '' },
        { id: 27, type: '' },
        { id: 28, type: '' },
        { id: 29, type: '' },
      ],
    },
    {
      id: 2,
      name: 'Mario Andrade',
      turn: 'T2',
      options: [
        { id: 0, type: '' },
        { id: 1, type: '' },
        { id: 2, type: '' },
        { id: 3, type: '' },
        { id: 4, type: '' },
        { id: 5, type: '' },
        { id: 6, type: '' },
        { id: 7, type: '' },
        { id: 8, type: 'T' },
        { id: 9, type: 'T' },
        { id: 10, type: 'T' },
        { id: 11, type: 'T' },
        { id: 12, type: 'T' },
        { id: 13, type: 'T' },
        { id: 14, type: 'T' },
        { id: 15, type: 'T' },
        { id: 16, type: 'T' },
        { id: 17, type: 'T' },
        { id: 18, type: 'T' },
        { id: 19, type: 'T' },
        { id: 20, type: 'T' },
        { id: 21, type: 'T' },
        { id: 22, type: 'T' },
        { id: 23, type: '' },
        { id: 24, type: '' },
        { id: 25, type: '' },
        { id: 26, type: '' },
        { id: 27, type: '' },
        { id: 28, type: '' },
        { id: 29, type: '' },
      ],
    },
  ],
  values: [
    {
      type: 'Qnt colab. ativos',
      value: [
        0, 1, 2, 2, 2, 2, 2, 2, 4, 3, 4, 4, 3, 2, 3, 3, 3, 3, 3, 2, 2, 2, 4, 3,
        3, 2, 2, 3, 4, 2,
      ],
    },
    {
      type: 'Qnt colab. ativos',
      value: [
        0, 1, 1, 1, 1, 1, 2, 2, 4, 3, 4, 9, 10, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3,
        3, 2, 2, 3, 1, 2,
      ],
    },
    {
      type: '% Cons. Ativos',
      value: [
        '0%',
        '98%',
        '98%',
        '98%',
        '98%',
        '98%',
        '98%',
        '98%',
        '98%',
        '98%',
        '100%',
        '100%',
        '100%',
        '100%',
        '133%',
        '100%',
        '133%',
        '100%',
        '100%',
        '100%',
        '100%',
        '100%',
        '100%',
        '100%',
        '98%',
        '100%',
        '100%',
        '133%',
        '100%',
        '100%',
      ],
    },
  ],
}
